name: Build statutes
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile PDF
        uses: xu-cheng/latex-action@master
        with:
          root_file: statutes.tex
          args: -pdf -file-line-error -synctex=1 -interaction=nonstopmode -file-line-error -recorder -f
        continue-on-error: true
      - name: Print LaTeX log
        shell: bash
        if: failure() || success()
        run: |
          value=`cat statutes.log`
          echo "$value"
      - name: Copy to output directory
        shell: bash
        if: failure() || success()
        run: |
          mkdir built
          mv statutes.pdf built/statutes.pdf
      - name: Upload PDF
        uses: actions/upload-artifact@v1.0.0
        if: failure() || success()
        with:
          # Artifact name
          name: Built Statutes
          # Directory containing files to upload
          path: ./built
