name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile statutes
        uses: xu-cheng/latex-action@master
        with:
          root_file: statutes.tex
          args: -pdf -file-line-error -synctex=1 -interaction=nonstopmode -file-line-error -recorder -f
      - uses: actions/upload-artifact@v1
        with:
          name: statutes.pdf
          path: statutes.pdf
